### ISSUE TITLE
Logo seems to be a plumaria or some other five petaled flower.

### ISSUE THREAD

**Issue by throughthetrees** [Vanilla-OS/plymouth-theme-vanilla#14]
Title says it.

Attached is a vanilla flower for reference. Vanilla flowers are 3 petals, three sepals, with one petal fusing with the column to form a labellum.

![IMG_20240319_113502431_HDR](https://github.com/user-attachments/assets/6d6cd6db-8c96-4081-b7f2-e1f043af481b)

**Comment by mirkobrombin** [comment]
Thanks for your interest, we really appreciate it, but we are not interested in changing the brand. The flower is stylized by choice.

**Comment by throughthetrees** [comment]
Claiming to represent "vanilla" but not actually using a vanilla orchid in the logo is both dishonest and appropriative. It undermines the authenticity of the brand by misleading users into believing that the logo accurately reflects the vanilla plant. This misrepresentation not only confuses users about what vanilla is but also disrespects the cultural and botanical significance of the vanilla orchid. Appropriating the name "vanilla" without honoring its true representation fails to acknowledge the heritage and importance of the plant, ultimately weakening the brand's integrity and trustworthiness.

Consider if the Linux developers claimed that Tux was a penguin but then used a pigeon as the mascot instead. Integrity of a brand is about the accuracy and authenticity of its representations. What would this tell us about the developers of Linux? Its not just about the logo being accurate (which is important), but also about what it says about the community behind a project. Is it important to them to "get things right", or do they consider things like accuracy in representation just of "throw away" value? Are these the kinds of people who just "use" representations but then abandon them when they see it as no longer valuable? This seems like a very extractive approach to identity.

I strongly advocate that you reconsider closing this issue, or at least perhaps leave the issue as available for future development. I get that you are trying to get an OS out, not fret about a flower. But that doesn't mean the issue can't be acknowledged and then addressed at some future date.

**Comment by mirkobrombin** [comment]
> dishonest

Sorry, but I’m not going to put more effort into this discussion. As I already mentioned, the logo is stylized by choice. Your lengthy response, full of arguments that we've already addressed, is not productive. It feels like you're being dishonest by forcing us to read and respond to a wall of text after we've given a clear answer. Our decision stands. 

Thank you again for your feedback, but this discussion will stay closed.
