### ISSUE TITLE
Provide a clean boot experience

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/plymouth-theme-vanilla#18]
Without the dash that appears before the splash screen shows and the dash that shows after. 

**How Fedora does it:**
Shows the manufacturer logo when the machine has reached grub without a flicker and you can hit I think F8 to show grub during that phase for a few seconds until the grub timeout finishes, then it turns off the screen and shows back up with the familiar Fedora BGRT spinner boot screen. When it reaches the graphical session, the spinner in the boot screen goes away, leaving only the BGRT and the distribution logo until the login manager appears.

This boot look looks much more pleasant and professional than the boot look in many other distros.

**Comment by axtloss** [comment]
its an explicit decision to show the grub menu, we're not reverting that part
and you already opened an issue about the plymouth screen in #17, nothing changed about what mirko said there

**Comment by ghost** [comment]
> its an explicit decision to show the grub menu, we're not reverting that part and you already opened an issue about the plymouth screen in #17, nothing changed about what mirko said there

The grub menu doesn't show up on my system, instead, the underline console cursor shows. Is that intended behavior?

**Comment by ghost** [comment]
> its an explicit decision to show the grub menu, we're not reverting that part and you already opened an issue about the plymouth screen in #17, nothing changed about what mirko said there

This one is for providing a clean boot experience, without the jarring transition to the console with the underline cursor appearing when the kernel loads the init (don't really know if that is the correct stage or not, correct if i am wrong) and when GDM starts. This will require using the BGRT spinner plymouth theme, and the `i915.fastboot=1`  kernel parameter as well as setting the GRUB menu to hidden mode in `/etc/grub/default` file, according to this [blog post](https://hansdegoede.livejournal.com/19224.html) anyway from a developer who contributes to Fedora.

**Comment by axtloss** [comment]
setting grub to hidden is something we explicitly dont want to do
our theme already is a bgrt theme
and the fastboot karg will not change a lot

i really do not consider some short cursor appearing jarring or unprofessional, it's not an issue

**Comment by ghost** [comment]
> setting grub to hidden is something we explicitly dont want to do our theme already is a bgrt theme and the fastboot karg will not change a lot

I am also using the vanilla-bgrt theme but the BGRT doesn't appear for me. Instead, I get this screen.

![IMG_20240915_200441](https://github.com/user-attachments/assets/cc72361d-c24a-4715-b6b9-12d0ed6f454c)

Is this the BGRT one? If not, how can I get it and why isn't it appearing (I dunno but maybe Secure Boot has to do something with it)?

**Comment by axtloss** [comment]
yes, because we disable bgrt, as i already said in the other issue you opened
its a custom bgrt theme, vanilla-bgrt
