### ISSUE TITLE
BGRT appears below throbber.

### ISSUE THREAD

**Issue by GittyMac** [Vanilla-OS/plymouth-theme-vanilla#8]
The boot screen seems to not hide the OEM logo, which causes it to appear below the Vanilla OS throbber. 

The BGRT screen seems to have been designed for full screen BGRT backgrounds which are fairly rare. Most BGRT logos, especially for devices designed for Windows, consist of the OEM's logo in the upper center portion of the screen, which is where the throbber is located.

**Comment by mirkobrombin** [comment]
Fixed by https://github.com/Vanilla-OS/live-iso/commit/7d379510b542d0a9591684d8b12f50283b0f59ab
